[package]
name = "wallya-scraper"
version = "0.1.0"
authors = ["StelarCF <StelarCF@gmail.com>"]

[dependencies]
hyper = "*"
rustc-serialize = "*"
time = "*"
xmlJSON = "*"
docopt = "*"
mqtt3 = "*"
tokio-core = "*"
futures = "0.1.14"
serde = "1.0.14"
serde_derive = "1.0.14"